### ISSUE TITLE
Incorrectly saved sprite

### ISSUE THREAD

**Issue by j-a-t-e** [Esshahn/spritemate#136] opened 2018-10-10 19:35 UTC
I've run into this issue once, and I have no idea how it happened. I have a project with eight sprites in it and they all have the same exact colors. In this particular project, sprite #6 gets an an extra pixel stored in the JSON file:

![kuva](https://user-images.githubusercontent.com/44037874/46761031-35a9ec00-ccdc-11e8-8187-a27b3a32c31e.png)

Looks like the editor is able to cope with that problem (probably just won't read that extra data), but I was able to notice this when an SPD export failed to load in SpritePad.

Unfortunately I don't think I can easily give you the necessary repro steps, because for the life of me, I have no idea how I managed to do this, but it wasn't by manually editing the .SPM file 😃 Maybe this is useful if someone reports problems with the SPD export, as that's where the bug seems to become visible.

P.S. thanks for the great app. Been having a lot of fun with it.

**Comment by j-a-t-e** [comment] 2018-10-10 19:58
Some more info: The sprite in question had been converted from what looks like an earlier version of the JSON format. Maybe the conversion is to blame, or perhaps the bug existed in an earlier version of the app -- impossible to tell, but hope this additional info is useful.

**Comment by Esshahn** [comment] 2018-10-11 11:53
Hey j-a-t-e, thank you for the bug report! I've received a similar description from nurpax before, so I know this bug exists. So far I haven't been lucky in finding the cause... If anything reproduceable comes up on your side, please let me know, that would help me a lot! Cheers

**Comment by Esshahn** [comment] 2019-05-01 14:07
Closing. The bug might still be in there, but I haven't had any success reproducing it nor did I receive any further bug reports. If it pops up again later I'll deal with it ;)

**Closed by Esshahn** 2019-05-01 14:07 UTC
